### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by persn** [Wano-k/MonoGame-3D-Game-Test#5]
The repo contains multiple user specific files, temp files, binaries and other annoyances that makes it difficult to work with. I suggest the following:
1. A gitignore for VisualStudio style projects should be made. [Like this one](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore)
2. Every file in the repo must be removed and then added again for full effect(files added before the gitignore was introduced will not be changed unless we do this)
3. The folder "Release" must be renamed to something else since Release is a keyword in C# that is included in most gitignores

**Comment by Wano-k** [comment]
Yep I did all the changes. I set "Release" directory to "Game"!
