### ISSUE TITLE
Excessive Garbage Collecting

### ISSUE THREAD

**Issue by persn** [Wano-k/MonoGame-3D-Game-Test#6]
The Visual Studio Profiler is showing that there is currently an excessive amount of Garbage Collecting occurring. The amount of GC triggering indicated by yellow dots is so frequent that it's impossible to distinguish them from another. I haven't investigated why this is happening.
![skjermbilde 2016-04-12 06 44 57](https://cloud.githubusercontent.com/assets/1510803/14450075/d76453a4-007a-11e6-80c8-b5c98de2f95c.png)

**Comment by Wano-k** [comment]
I think that I know why I'm having that. I'll take a look tomorrow.

**Comment by Wano-k** [comment]
Got it, it was a list of vertices converted to an array into each drawings. Should be better now. Thanks!
